/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BlfSee7jYQ6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { useEffect, useState } from "react";

export default function HomePage1() {
  const [currentBgUrl, setCurrentBgUrl] = useState("/images/waterday/IMG_8130.JPG");

  useEffect(() => {
    let currentIndex = 0;
    const backgrounds = [
      "/images/waterday/IMG_8130.JPG",
      "/images/waterday/IMG_8192.JPG",
      "/images/waterday/IMG_8215.JPG",
      "/images/waterday/IMG_8219.JPG",
      "/images/waterday/IMG_8240.JPG",
      "/images/waterday/IMG_8293.JPG",
      "/images/waterday/IMG_8319.JPG",
      "/images/waterday/IMG_8337.JPG",
      "/images/waterday/IMG_8398.JPG",
      "/images/waterday/IMG_8538.JPG",
      "/images/waterday/IMG_8879.JPG",
      "/images/waterday/IMG_8919.JPG",
      "/images/waterday/IMG_8951.JPG",
      "/images/waterday/IMG_8955.JPG",
    ];

    const changeBackground = () => {
      const showDuration = 2000; // Show each image for 2 seconds
      const pauseDuration = 8000; // Pause for 8 seconds

      setCurrentBgUrl(backgrounds[currentIndex]);
      setTimeout(() => {
        currentIndex++;
        if (currentIndex >= backgrounds.length) {
          currentIndex = 0; // Loop back to the start
        }
        changeBackground(); // Call the function again after the pause
      }, showDuration + pauseDuration);
    };

    changeBackground(); // Start the animation
  }, []);
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <section
        className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-cover bg-center flex justify-center fade-bg"
        style={{ backgroundImage: `url(${currentBgUrl})` }}>
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center text-center space-y-4">
            <h1 className="text-4xl font-bold tracking-tighter text-primary-foreground sm:text-5xl md:text-6xl">
              Welcome to Our Church
            </h1>
            <p className="max-w-[600px] text-primary-foreground md:text-xl">
              Discover the warmth and community of our vibrant church. Join us for worship, fellowship, and spiritual
              growth.
            </p>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}>
              Learn More
            </Link>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 flex justify-center">
        <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">About Our Church</h2>
            <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Our church has a rich history of serving the community and providing a welcoming space for spiritual
              growth. We believe in the power of faith, fellowship, and making a positive impact in the world.
            </p>
          </div>
          <div className="flex flex-col gap-2 min-[400px]:flex-row lg:justify-end">
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}>
              Our Beliefs
            </Link>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}>
              Our History
            </Link>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted flex justify-center">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Upcoming Events</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Join Us for Upcoming Events</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Check out our upcoming events and activities. We have something for everyone, from worship services to
                community outreach programs.
              </p>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
            <img
              src="/images/preaching.jpeg"
              width="550"
              height="310"
              alt="Event"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            />
            <div className="flex flex-col justify-center space-y-4">
              <ul className="grid gap-6">
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Sunday Worship</h3>
                    <p className="text-muted-foreground">
                      Join us every Sunday at 10 AM for our weekly worship service.
                    </p>
                  </div>
                </li>
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Bible Study</h3>
                    <p className="text-muted-foreground">
                      Dive deeper into the Word of God with our weekly Bible study group.
                    </p>
                  </div>
                </li>
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Community Outreach</h3>
                    <p className="text-muted-foreground">
                      Join us as we serve our local community through various outreach programs.
                    </p>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 border-t flex justify-center">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Get in Touch</h2>
            <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Have any questions or want to learn more about our church? Contact us using the form below.
            </p>
          </div>
          <div className="mx-auto w-full max-w-sm space-y-2">
            <form className="flex flex-col gap-2">
              <Input
                type="text"
                placeholder="Name"
                className="max-w-lg"
              />
              <Input
                type="email"
                placeholder="Email"
                className="max-w-lg"
              />
              <Textarea
                placeholder="Message"
                className="min-h-[100px] max-w-lg"
              />
              <Button type="submit">Submit</Button>
            </form>
          </div>
        </div>
      </section>
    </div>
  );
}
