/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BlfSee7jYQ6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { useEffect, useState } from "react";

export default function HomePage1() {
  const [currentBgUrl, setCurrentBgUrl] = useState("/images/waterday/IMG_8130.JPG");
  const [currentIndex, setCurrentIndex] = useState(1);

  useEffect(() => {
    const backgrounds = [
      "/images/waterday/IMG_8130.JPG",
      "/images/waterday/IMG_8192.JPG",
      "/images/waterday/IMG_8240.JPG",
      "/images/waterday/IMG_8293.JPG",
      "/images/waterday/IMG_8337.JPG",
      "/images/waterday/IMG_8398.JPG",
      "/images/waterday/IMG_8538.JPG",
      "/images/waterday/IMG_8879.JPG",
      "/images/waterday/IMG_8919.JPG",
    ];

    const changeBackground = () => {
      console.log("Changing background");
      setTimeout(() => {
        setCurrentBgUrl(backgrounds[currentIndex]);
        setCurrentIndex(currentIndex + 1);
        if (currentIndex >= backgrounds.length - 1) {
          setCurrentIndex(0); // Loop back to the start
        }
      }, 12000);
    };

    changeBackground();
  }, [currentBgUrl]);
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header
        className="py-4 px-6 flex items-center justify-between w-screen"
        style={{ color: "#0b4465", backgroundColor: "rgba(255, 255, 255, 0.4);", position: "absolute" }}>
        <Link
          href="#"
          className="flex items-center gap-2"
          prefetch={false}>
          <img
            src="/icons/familyLife-logo.png"
            alt="Family Life Church Logo"
            className="h-8 w-8"
          />
          <span
            className="text-l font-bold sm:text-xl md:text-2xl"
            style={{ fontFamily: "sinkin_sans600_semibold", color: "#0b4465" }}>
            FAMILY LIFE CHURCH
          </span>
        </Link>
        <nav className="hidden md:flex items-center gap-6">
          <Link
            href="#"
            className="hover:underline underline-offset-4"
            prefetch={false}>
            About
          </Link>
          <Link
            href="#"
            className="hover:underline underline-offset-4"
            prefetch={false}>
            Services
          </Link>
          <Link
            href="#"
            className="hover:underline underline-offset-4"
            prefetch={false}>
            Contact
          </Link>
        </nav>
        <Button
          variant="secondary"
          className="md:hidden">
          {/* <MenuIcon className="h-6 w-6" /> */}
          <span className="sr-only">Toggle menu</span>
        </Button>
      </header>
      <section
        className="w-full pb-12 pt-20 md:pb-24 md:pt-32 lg:pb-32 lg:pt-40 xl:pb-48 xl:pt-56 bg-cover bg-center flex justify-center items-center"
        style={{
          backgroundImage: `url(${currentBgUrl})`,
          transition: "background-image 3s ease-in-out 3s",
          height: "80vh",
        }}>
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center text-center space-y-4">
            <h1
              className="text-2xl font-bold tracking-normal text-primary-foreground sm:text-4xl md:text-6xl drop-shadow-lg"
              style={{ fontFamily: "sinkin_sans600_semibold" }}>
              BY THE WORD OF GOD
            </h1>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}>
              Learn More
            </Link>
            <p className="max-w-[600px] text-primary-foreground md:text-xl drop-shadow-lg">
              A new church plant in Iva, SC!
              <br /> Here to serve Jesus and this community!
            </p>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 flex justify-center">
        <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">About Our Church</h2>
            <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Our church has a rich history of serving the community and providing a welcoming space for spiritual
              growth. We believe in the power of faith, fellowship, and making a positive impact in the world.
            </p>
          </div>
          <div className="flex flex-col gap-2 min-[400px]:flex-row lg:justify-end">
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}>
              Our Beliefs
            </Link>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}>
              Our History
            </Link>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted flex justify-center">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Upcoming Events</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Join Us for Upcoming Events</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Check out our upcoming events and activities. We have something for everyone, from worship services to
                community outreach programs.
              </p>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
            <img
              src="/images/preaching.jpeg"
              width="550"
              height="310"
              alt="Event"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
            />
            <div className="flex flex-col justify-center space-y-4">
              <ul className="grid gap-6">
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Sunday Worship</h3>
                    <p className="text-muted-foreground">
                      Join us every Sunday at 10 AM for our weekly worship service.
                    </p>
                  </div>
                </li>
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Bible Study</h3>
                    <p className="text-muted-foreground">
                      Dive deeper into the Word of God with our weekly Bible study group.
                    </p>
                  </div>
                </li>
                <li>
                  <div className="grid gap-1">
                    <h3 className="text-xl font-bold">Community Outreach</h3>
                    <p className="text-muted-foreground">
                      Join us as we serve our local community through various outreach programs.
                    </p>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 border-t flex justify-center">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Get in Touch</h2>
            <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Have any questions or want to learn more about our church? Contact us using the form below.
            </p>
          </div>
          <div className="mx-auto w-full max-w-sm space-y-2">
            <form className="flex flex-col gap-2">
              <Input
                type="text"
                placeholder="Name"
                className="max-w-lg"
              />
              <Input
                type="email"
                placeholder="Email"
                className="max-w-lg"
              />
              <Textarea
                placeholder="Message"
                className="min-h-[100px] max-w-lg"
              />
              <Button type="submit">Submit</Button>
            </form>
          </div>
        </div>
      </section>
    </div>
  );
}
